kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../base

namespace: stage-prod

commonLabels:
  app.kubernetes.io/name: webserver

images:
- name: webserver
  newName: quay.io/danielstraub/webserver
  newTag: "2.0"

configMapGenerator:
- name: webserver
  files:
  - env.properties

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env
      value:
      - name: COURSE
        value: DO288-Prod
  target:
    kind: Deployment
- patch: |-
    kind: Ingress
    apiVersion: networking.k8s.io/v1
    metadata:
      name: webserver
    spec:
      rules:
      - host: stage-prod.k8s.straubcloud.de
        http:
          paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: webservice
                port:
                  number: 80

