kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../base

namespace: stage-prod

commonLabels:
  app.kubernetes.io/name: webserver

images:
- name: webserver
  newName: quay.io/danielstraub/webserver
  newTag: "2.1"

configMapGenerator:
- name: webserver
  files:
  - env.properties

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env
      value:
      - name: COURSE
        value: DO288-Prod
  target:
    kind: Deployment
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: stage-prod.k8s.straubcloud.de
  target:
    kind: Ingress

