kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../base

namespace: stage-prod

labels:
  - pairs:
      app.kubernetes.io/name: webserver
    includeSelectors: true

generatorOptions:
  labels:
    app.kubernetes.io/name: webserver

images:
- name: webserver
  newName: registry.straubcloud.de/webserver

configMapGenerator:
- files:
  - env.properties
  name: webserver

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env
      value:
      - name: COURSE
        value: DO288-Prod
  target:
    kind: Deployment
- patch: |-
    kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: webserver
    spec:
      host: stage-prod.ocp.straubcloud.de
