kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../base

namespace: stage-prod

commonLabels:
  app.kubernetes.io/name: webserver

images:
- digest: sha256:49297378194c3c41334a045e987be1890e290aa0090ab148edeb0927acc5befc
  name: webserver
  newName: registry.straubcloud.de/webserver

configMapGenerator:
- files:
  - env.properties
  name: webserver

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env
      value:
      - name: COURSE
        value: DO180-Prod
  target:
    kind: Deployment
- patch: |-
    kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: webserver
    spec:
      host: stage-prod.ocp.straubcloud.de
