apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: webserver
  labels:
    template: webserver
parameters:
- name: stage
  required: true  
- name: course
  required: true
- name: version
  value: latest
labels:
  app: webserver
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: webserver
    namespace: stage-${stage}
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: webserver
    template:
      metadata:
        labels:
          app: webserver
      spec:
        containers:
        - name: webserver
          image: registry.straubcloud.de/webserver:${version}
          env:
          - name: COURSE
            value: ${course}
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
- apiVersion: v1
  kind: Service
  metadata:
    name: webserver
    namespace: stage-${stage}
  spec:
    selector:
      app: webserver
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: webserver
    namespace: stage-${stage}
  spec:
    host: webserver-${stage}.ocp.straubcloud.de
    to:
      kind: Service
      name: webserver
    port:
      targetPort: http
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect

