kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- vault.yml
- agent.yml
- test.yml
- service.yml
- route.yml
- pvc.yml
- sa.yml

namespace: vault

commonLabels:
  app.kubernetes.io/instance: vault

configMapGenerator:
- name: vault
  files:
  - vault-server=vault-server.conf 
  - vault-agent=vault-agent.conf 

