kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: volume-1
  labels:
    app: volume-1
spec:
  volumeName: volume-1
  storageClassName: ""
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi

