apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage-test
  namespace: gitops
spec:
  destination:
    namespace: stage-test
    server: https://kubernetes.default.svc
  project: default
  source:
    path: webserver/kustomize/overlays/test
    repoURL: git@github.com:dstraub/lab-sample.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: false

