apiVersion: v1
kind: Namespace
metadata:
  labels:
    ext-secret-registry-conf: "true"
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/audit-version: baseline
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/warn-version: baseline
  name: odo
spec:
  finalizers:
  - kubernetes
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: app
    app.kubernetes.io/instance: springboot
    app.kubernetes.io/managed-by: odo
    app.kubernetes.io/managed-by-version: v3.16.1
    app.kubernetes.io/part-of: app
    app.openshift.io/runtime: springboot
    component: springboot
    odo.dev/mode: Dev
  name: springboot-app
spec:
  host: springboot-app.ocp.straubcloud.de
  port:
    targetPort: https
  tls:
    termination: edge
  to:
    kind: Service
    name: springboot-app
    weight: 100
  wildcardPolicy: None
