apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: trigger-argo
spec:
  params:
  - name: application
    type: string
  - name: timeout 
    type: string
    default: "60"
  - name: revision
    type: string
    default: HEAD
  stepTemplate:
    envFrom:
    - secretRef:
        name: gitops-admin
  steps:
  - image: quay.io/argoproj/argocd
    script: |
      yes | argocd login "$ARGOCD_SERVER" --username="$ARGOCD_USERNAME" --password="$ARGOCD_PASSWORD"
      set -x
      argocd app sync $(params.application) --revision $(params.revision) --timeout=$(params.timeout)
      argocd app wait $(params.application) --sync  --timeout=$(params.timeout)
      argocd app wait $(params.application) --health  --timeout=$(params.timeout)

